### ISSUE TITLE
Demo doesnt work

### ISSUE THREAD

**Issue by darklilium** [dmotz/thing-translator#1]
Hello,
I was seeing ur project and i wanted to try the demo but it is not working.

**Comment by dmotz** [comment]
Could you elaborate? What browser/OS?

**Comment by darklilium** [comment]
Windows 10, google chrome.
![image](https://cloud.githubusercontent.com/assets/8507515/20359610/6c894d5a-ac0f-11e6-8766-aa8c15d86831.png)

**Comment by dmotz** [comment]
Could you clear your cache and try it again? I pushed a change that may help.

**Comment by darklilium** [comment]
It may help, but right now i dont have any camera in this computer so i cannot try.
So maybe it will be useful some advice on the page when u cannot use this app without a camera.

![image](https://cloud.githubusercontent.com/assets/8507515/20361473/72d0b7dc-ac16-11e6-991e-2de26b4f3d87.png)

![image](https://cloud.githubusercontent.com/assets/8507515/20361496/8f0aaca0-ac16-11e6-9787-b2c94ab03794.png)

Thanks and great job :)

**Comment by dmotz** [comment]
I just made another update so you should see a message now in your case. Let me know if that works.

Thanks for your help.

**Comment by darklilium** [comment]
No problem!
The message works perfectly, when i go home i will check the app with the camera :).
