### ISSUE TITLE
Too quick to label an object as a weapon. -be careful what that code is used for.

### ISSUE THREAD

**Issue by elhippiesupremo** [dmotz/thing-translator#12]
When I held up a harmonica, it says weapon. Checking the harmonica a second time yields 'pistol'. When I held up a pen, it says weapon. Be careful what that code is used for.

**Comment by dmotz** [comment]
Sounds like you're bumping into the current pitfalls of AI. It's possible the machine thought of your harmonica in this sense: https://en.wikipedia.org/wiki/This_machine_kills_fascists
