### ISSUE TITLE
Chromium Web Browser Camera Issues on Raspbian Jessie (RPI3)

### ISSUE THREAD

**Issue by kaisark** [dmotz/thing-translator#15]
Does this app work on Raspbian Jessie 8 (Raspberry Pi 3 - ARM) and the Chromium web browser? It seems like the browser prompts the user to allow for camera access but camera image does not render in the browser frame after access is allowed...

localhost:9966

Thanks.

**Comment by dmotz** [comment]
Any console errors?

**Comment by kaisark** [comment]
Console Log (see below) does not show any errors. Works on Chromium v60.0.3112 on my Jetson TX1. Might be a Chromium issue on the RPI...

Chromium:
Version 51.0.2704.91 Built on Ubuntu 14.04, running on Raspbian 8.0

------------------------------------------------------------
pi@rpi1:\~ $ cd thing-translator/
pi@rpi1:\~/thing-translator $ ls
app.css  index.html  node_modules  README.md  style
app.js   LICENSE     package.json  src
pi@rpi1:\~/thing-translator $ npm run dev

> thing-translator@0.0.1 dev /home/pi/thing-translator
> parallelshell 'npm run watch' 'npm run watch-style'


> thing-translator@0.0.1 watch-style /home/pi/thing-translator
> stylus -c -u nib -w style/main.styl -o app.css


> thing-translator@0.0.1 watch /home/pi/thing-translator
> budo src/app.js --live --host localhost -- -t babelify

[0002] info  Server running at http://localhost:9966/ (connect)
[0002] info  LiveReload running
  watching /home/pi/thing-translator/node_modules/stylus/lib/functions/index.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/index.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/border.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/border-radius.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/clearfix.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/color-image.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/flex.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/gradients.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/config.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/iconic.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/image.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/normalize/index.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/normalize/base.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/normalize/html5.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/normalize/links.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/normalize/text.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/normalize/embed.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/normalize/groups.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/normalize/forms.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/normalize/tables.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/overflow.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/positions.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/reset.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/text/index.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/text/aliases.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/text/ellipsis.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/text/hide-text.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/text/replace-text.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/text/shadow-stroke.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/vendor.styl
  watching /home/pi/thing-translator/node_modules/nib/lib/nib/size.styl
  compiled app.css
  watching style/main.styl
[0013] 11.1s      712KB (browserify)
[0051] 33ms          0B GET    304 /
[0051] 2ms        712KB GET    200 /app.js
[0051] 39ms        12KB GET    200 /app.css



![screenshot-localhost-9966-2017-09-19-15-23-46-173](https://user-images.githubusercontent.com/3580312/30611620-decdfe92-9d4f-11e7-9776-032d1a41528e.png)

**Comment by kaisark** [comment]
I think the RPI Raspbian Jessie has an older Chromium browser version so I moved on...

I was able to get the build working (camera loading in browser and translation processing) on my Nvidia TX1 a few times before the system froze. I had to reboot (new job added to startup I noticed - nodejs???) and after launching the app again (npm run dev), I ran into the browser camera security issue...

chrome: Version 61.0.3163.100 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

Anyway, the app idea is good but working through the browser might cause too many support issues...

Cheers!  

![screenshot from 2017-10-18 16-04-33](https://user-images.githubusercontent.com/3580312/31740127-53662e70-b41e-11e7-95a6-00c65d44c9f5.png)
