### ISSUE TITLE
App doesn't work

### ISSUE THREAD

**Issue by DavidDonovski** [dmotz/thing-translator#19]
Can you re-check if everything's working on your side? All I'm getting is the failureState.

**Comment by dmotz** [comment]
What browser are you using?

**Comment by DavidDonovski** [comment]
Google Chrome. I had to remove the screw-ie8 option and the sed command in order to make 'npm run bundle' run successfully, though, so I don't know if that may be causing it.

**Comment by dmotz** [comment]
Make sure to set your own API key in `config.js` for dev builds or in a file called `api_key` in the root when running `bundle`.
