### ISSUE TITLE
Pronunciation 

### ISSUE THREAD

**Issue by esthermurillo** [dmotz/thing-translator#2]
I know this is not a technical issue exactly. But while giving the app a try I noticed that at least for the Spanish pronunciations almost all of them were incorrect. It's clear that the app's learned language skills are based on English phonemes which is distinctly obvious with the vowels. 
Just figured for a translator it's a noticeable factor.

**Comment by dmotz** [comment]
Great point. The pronunciations used are entirely dependent on what particular speech synthesis capabilities and language packs your device has installed. For instance on my laptop running Chrome on macOS, there's a different language-specific voice for each of the languages Thing Translator offers. On many Androids this is also the case, but the voices will be different from their Mac counterparts.

Did you notice that the same voice was used for reading both Spanish and English in your case?

**Comment by esthermurillo** [comment]
Yes, it was the same female voice for both. I am using a work-issued Lenovo ThinkPad running Chrome, so I'll be giving it a try on my personal laptop later on tonight.
