### ISSUE TITLE
thing-translator.appspot.com not working

### ISSUE THREAD

**Issue by kikeelectronico** [dmotz/thing-translator#27]
HI,

Looks like the version deployed at [thing-translator.appspot.com/](https://thing-translator.appspot.com/) has a problem with its Google Vision API key. THe query to vision returns a 400 error with the following body.

```
{
  "error": {
    "code": 400,
    "message": "API key expired. Please renew the API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "vision.googleapis.com"
        }
      }
    ]
  }
}
```

**Comment by dmotz** [comment]
Thanks for bringing this to my attention, the live demo should be working again now.
