### ISSUE TITLE
? Appearing when using web-app demo

### ISSUE THREAD

**Issue by rpawlyv** [dmotz/thing-translator#28]
On certain days when I use this app I get ? when taking any pictures- the app is using the camera fine during this. Vision and Translate API don't happen to be down or anything when this happens. Not sure how often this occurs but the downtime seems to be 1-2 days sometimes every couple of weeks or so.

**Comment by MistaSee** [comment]
Bump to this one. :) I can't get it to work either. More and more regularly.

**Comment by rpawlyv** [comment]
Thanks for the bump! If you are interested in interacting with Google Cloud and Translate APIs, the Woolaroo app that was in the same Google Experiment program is still running smooth. It uses multi-object detection which is neat, but it is more of an art/culture project since it uses endangered languages instead of common ones.

**Comment by dmotz** [comment]
The app should be working correctly now.
