### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by matthijswardenier** [dmotz/thing-translator#8]
Really new to this, got it running, but is only showing me a black screen in the browser. Am I doing something wrong? Thanks for your help!
<img width="1280" alt="screen shot 2016-11-26 at 18 48 17" src="https://cloud.githubusercontent.com/assets/24192635/20642210/097b6070-b409-11e6-9d6b-ef5f89c6cd0c.png">

**Comment by matthijswardenier** [comment]
Managed to fix it

**Comment by matthijswardenier** [comment]
Have another issue now, seems like the API key isn't set for cloud vision API. Do I need to create one for own use?

**Comment by matthijswardenier** [comment]
Fixed it, works!! Really cool 👍

**Comment by harshjv** [comment]
@matthijswardenier How did you fix it?
